title = "Repli"  # From Git
gitRepoUrl = "https://github.com/Kumarion/Repli" # From Git

gitSourceBranch = "main"
changelog = true

[[classOrder]]
section = "Repli"
classes = ["RepliClient", "RepliServer"]

[[classOrder]]
section = "Util"
classes = ["Promise", "Signal", "Error"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Kumarion"
projectName = "Repli"
url = "https://kumarion.github.io"
baseUrl = "/Repli/"
tagline = "Your project's tagline"

[footer]
style = "dark"
copyright = "Copyright © 2023 Kumarion. Built with Moonwave and Docusaurus"